### ISSUE TITLE
How to add layer to nxp soc?

### ISSUE THREAD

**Issue by herryliq** [willstott101/meta-mediapipe#1]
I am a newer ablout yocto build system, I want add this repo to nxp soc board, 
like this:
`BBLAYERS += " ${BSPDIR}/sources/poky/meta-mediapipe "
`

but I get some error:
```

--- Starting bitbake server pid 24682 at 2022-10-17 07:03:40.985098 ---
ERROR: Layer meta-tensorflow is not compatible with the core layer which only supports these series: zeus (layer is compatible with hardknott)
```

Can you give me some suggestion? Best regards.

**Comment by willstott101** [comment]
I'm not an expert but you could try changing: https://github.com/willstott101/meta-mediapipe/blob/master/conf/layer.conf#L14

**I'm not suggesting this layer is compatible** - but you can try telling bitbake it is and see what happens.
